import { TVInfo } from '@/features/home/services/@types/tmdb.types';

export const tvInfo: TVInfo = {
	adult: false,
	backdrop_path: '/path/to/backdrop.jpg',
	created_by: [],
	episode_run_time: [60],
	first_air_date: '2022-01-01',
	genres: [
		{ id: 1, name: 'Drama' },
		{ id: 2, name: 'Action' },
	],
	homepage: 'https://example.com',
	id: 123,
	in_production: true,
	languages: ['en'],
	last_air_date: '2022-12-31',
	last_episode_to_air: {
		id: 1001,
		name: 'Finale',
		overview: 'The final episode of the season.',
		vote_average: 8.5,
		vote_count: 100,
		air_date: '2022-12-31',
		episode_number: 10,
		episode_type: 'standard',
		production_code: 'S1E10',
		runtime: 60,
		season_number: 1,
		show_id: 123,
		still_path: '/path/to/still.jpg',
	},
	name: 'Example Show',
	next_episode_to_air: null,
	networks: [{ id: 1, name: 'Network 1', logo_path: '/path/to/logo1.png', origin_country: 'US' }],
	number_of_episodes: 10,
	number_of_seasons: 1,
	origin_country: ['US'],
	original_language: 'en',
	original_name: 'Example Show',
	overview: 'This is an example show.',
	popularity: 100.0,
	poster_path: '/path/to/poster.jpg',
	production_companies: [
		{ id: 1, name: 'Production Company 1', logo_path: '/path/to/logo1.png', origin_country: 'US' },
	],
	production_countries: [{ iso_3166_1: 'US', name: 'United States' }],
	seasons: [
		{
			air_date: '2022-01-01',
			episode_count: 10,
			id: 2001,
			name: 'Season 1',
			overview: 'The first season of the show.',
			poster_path: '/path/to/season1.jpg',
			season_number: 1,
			vote_average: 8.0,
		},
	],
	spoken_languages: [{ english_name: 'English', iso_639_1: 'en', name: 'English' }],
	status: 'Returning Series',
	tagline: 'An example tagline.',
	type: 'Scripted',
	vote_average: 8.5,
	vote_count: 1000,
};
